server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v*/user/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v*/product/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v*/order/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/v*/delivery/**

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
