playground:
  title: Gateway Server
  version: 1.0.0

server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 20
        max-interval: 2000
        multiplier: 1.1
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v*/users/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v*/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v*/orders/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/v*/deliveries/**

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
