version: '3.8'

services:
  playground-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_flyway
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - 3308:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d

  config-server:
    image: config-server-image
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - playground-mysql

  discovery-server:
    image: discovery-server-image
    restart: always
    environment:
      - spring.profiles.active=local
      - CONFIG_SERVER_URI=http://config-server:8888
    ports:
      - 8761:8761
    depends_on:
      - config-server

  gateway-server:
    image: gateway-server-image
    restart: always
    environment:
      - spring.profiles.active=local
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka/
    ports:
      - 8080:8080
    depends_on:
      - discovery-server

  user-service:
    image: user-service-image
    restart: always
    environment:
      - spring.profiles.active=local
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka/
      - PLAYGROUND_MYSQL_URI=playground-mysql:3306
    ports:
      - 8081:8080
    depends_on:
      - gateway-server

  product-service:
    image: product-service-image
    restart: always
    environment:
      - spring.profiles.active=local
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka/
      - PLAYGROUND_MYSQL_URI=playground-mysql:3306
    ports:
      - 8082:8080
    depends_on:
      - gateway-server

  order-service:
    image: order-service-image
    restart: always
    environment:
      - spring.profiles.active=local
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka/
      - PLAYGROUND_MYSQL_URI=playground-mysql:3306
    ports:
      - 8083:8080
    depends_on:
      - gateway-server

  delivery-service:
    image: delivery-service-image
    restart: always
    environment:
      - spring.profiles.active=local
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka/
      - PLAYGROUND_MYSQL_URI=playground-mysql:3306
    ports:
      - 8084:8080
    depends_on:
      - gateway-server
