playground:
  title: Discovery Server
  version: 1.0.0

server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 20
        max-interval: 2000
        multiplier: 1.1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
