spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/db_product?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false&cacheDefaultTimezone=false&allowMultiQueries=true
    username: app_playground
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

logging:
  level:
    root: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
