playground:
  title: Product API
  version: 1.0.0

server:
  port: 8080

spring:
  application:
    name: product-service
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 20
        max-interval: 2000
        multiplier: 1.1

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true

springdoc:
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
  paths-to-match:
    - /**

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
