spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true

logging:
  level:
    root: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
