spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/db_playground?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false&cacheDefaultTimezone=false&allowMultiQueries=true
    username: app_playground
    password: password
  flyway:
    locations: classpath:db/migration
