playground:
  title: Config Server
  version: 1.0.0

server:
  port: 8888

spring:
  profiles:
    active:
      - native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/

jwt:
  access-token-validity: ${ACCESS_TOKEN_VALIDITY:3600}
  refresh-token-validity: ${REFRESH_TOKEN_VALIDITY:43200}
  secret: ${JWT_SECRET:9e8275a1552f04233a54c11a76a39095c502aa4f58cc20cf4b02b36e73b2c90e}
