server:
  port: 8080

spring:
  application:
    name: delivery-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

playground:
  title: Delivery API
  version: 1.0.0

springdoc:
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
  paths-to-match:
    - /**

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
